### ISSUE TITLE
постерная сессия

### ISSUE THREAD

**Issue by dkagramanyan** [dkagramanyan/wc_cv#11]
Нужно загрузить в cabinet.miem постер. На диске лежит постер прошлого года, его можно взять за основу. 
Напечатать постер нужно своими ручками (bruh)

"​​ !Постер макетируется и тиражируется силами Проектной команды."

Дедлайн - 23 января 23:59.

https://miem.hse.ru/project_office/announcements/551864575.html
https://miem.hse.ru/project_office/poster

- [x] сделать постер (на диске есть материалы постерной сессии прошлого года)

**Comment by lizaconst** [comment]
брух

**Comment by dkagramanyan** [comment]
глобальные цели:
- выделить на снимках микроструктур регионы, ответственные за свойства сплава
- изучить природу сечения многогранников
- изучить взаимосвязь между параметрами сплава 
- найти способ выявления скрытых зависимостей между физическими характеристиками сплава при помощи нейронных сетей

план:
- применение автоэнкодера и анализ результатов
- генерация снимков микроструктур с заданными параметрами в Blender
- мат. моделирование сечений в многогранниках
