### ISSUE TITLE
Полезные ссылки

### ISSUE THREAD

**Issue by dkagramanyan** [dkagramanyan/wc_cv#14]
- [ ] normalizing flow https://github.com/janosh/awesome-normalizing-flows
- [ ] weight decay https://towardsdatascience.com/this-thing-called-weight-decay-a7cd4bcfccab
- [ ] разные распределения матстат https://habr.com/ru/post/311092/
- [ ] вариационный инференс https://habr.com/ru/post/471890/
- [ ] cvae https://github.com/EleMisi/ConditionalVAE
- [ ] pointer value retrieval https://arxiv.org/pdf/2107.12580.pdf
- [ ] stylegan3, alias free https://arxiv.org/pdf/2106.12423.pdf
- [ ] автоэнкодеры подробно https://lilianweng.github.io/posts/2018-08-12-vae/

Гугл диск https://drive.google.com/drive/folders/1jjqD2ugV1LY20S1N8Jj4xifCWH_pN4HN

Zoom https://zoom.us/j/99690013006

**Comment by lizaconst** [comment]
ещё бы сюда ссылку на зум добавить и на гугл диск! каждый раз ищу!

**Comment by dkagramanyan** [comment]
> ещё бы сюда ссылку на зум добавить и на гугл диск! каждый раз ищу! 

Ок
